### ISSUE TITLE
Error when I start backup container

### ISSUE THREAD

**Issue by Rbourree** [confirm/docker-mysql-backup#11]
I, when i start my backup container logs say:

`** (mydumper:18): CRITICAL **: Error connecting to database: Unknown MySQL server host '-P' (13)`

My docker-compose.yml file:

`services:

    db:
        image: mysql
        container_name: Mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpMyAdmin
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8080:80
        links:
            - db:db

    backup:
        image: confirm/mysql-backup
        container_name: backup_mysql
        restart: "no"
        links:
            - db
        volumes:
            - ./backups:/backup
        environment:
            db_ENV_MYSQL_DATABASE: wever
            db_ENV_MYSQL_ROOT_PASSWORD: root`

**Comment by domibarton** [comment]
I think this is because of the trailing quote behind `root`:

```
db_ENV_MYSQL_ROOT_PASSWORD: root`
```
