### ISSUE TITLE
Can it backup all Dbs ?

### ISSUE THREAD

**Issue by pascalandy** [confirm/docker-mysql-backup#4]
Hi,
I want to do a dumpall. Not only one at a time.

<CONTAINER>_ENV_MYSQL_DATABASE
<CONTAINER>_ENV_MYSQL_ROOT_PASSWORD

Is it supported ?

**Comment by chrisnew** [comment]
I ran into the same issue yesterday and openen a PR to allow dumping all databases. I hope the maintainer will merge it. :)

**Comment by domibarton** [comment]
He will… :)

**Comment by domibarton** [comment]
He did! :)
