### ISSUE TITLE
Get ready for Doker Swarm 1.12+

### ISSUE THREAD

**Issue by pascalandy** [confirm/docker-mysql-backup#5]
Since compose V2 and Docker Swarm --link is not existing anymore. 

Would be nice to adapt it :)

Here is what I have in mind:

```
CTN_NAME=mysqlbkp2
HUB_IMAGE=confirm/mysql-backup:v1.1.0

docker service create \
    --name $CTN_NAME \
    --network sqlnet \
    --mount type=bind,src=/var/lib/mysql/backup,dst=/backup \
    --constraint node.labels.type==db \
    --restart-condition any \
$HUB_IMAGE sleep 3600
```

**Comment by domibarton** [comment]
Sorry for the late reply. I'm far away from Docker nowadays, thus I need to update my knowledge quite a bit ^^ 

Are you interested in creating a new PR for this (even after 3 yrs… sry ^^)?

**Comment by pascalandy** [comment]
no I'm good. Thanks!
