### ISSUE TITLE
Question: simultaneous dump and restore? 

### ISSUE THREAD

**Issue by jauyzed** [confirm/docker-mysql-backup#9]
Can I run these containers to do a simultaneous dump and restore? 
I run migrations from prod db--> dev.db  The way i achieve it is using 2 separate container tasks . One for dumping from prod and one for restoring to dev. I want to combine them both to achieve something like `mysqldump | mysql` using docker + volume containers.

**Comment by domibarton** [comment]
Mhm this container doesn't use `mysqldump` and I'm note sure if `mydumper` can achieve this. Of course that would be a nice feature and I'd looking forward to get a PR for it :)
